-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        allow_tearing = true,
        border_size = 0,
    },
})

-- Keybinds
hl.unbind("SUPER + c")
hl.bind("SUPER + W", hl.dsp.window.close())
hl.unbind("SUPER + E")
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("dolphin"))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("flatpak run net.imput.helium & disown"))
